export const AttachmentType = {
  DRAWING: "DRAWING",
  CUBE_7_DAY: "CUBE_7_DAY",
  CUBE_28_DAY: "CUBE_28_DAY",
  INTEGRITY_TEST: "INTEGRITY_TEST",
  ECCENTRICITY_CHECK: "ECCENTRICITY_CHECK",
  PILE_READING: "PILE_READING",
  RCC_DRAWING: "RCC_DRAWING",
  ARCHITECT: "ARCHITECT",
  MEP_DRAWING: "MEP_DRAWING",
  RCC_CONSULTANT_REPORT: "RCC_CONSULTANT_REPORT",
  ARCHITECT_CONSULTANT_REPORT: "ARCHITECT_CONSULTANT_REPORT",
  SITE_IMG: "SITE_IMG",
  PROFILE_IMG: "PROFILE_IMG",
  OTHER: "OTHER",
} as const;

export type AttachmentType = (typeof AttachmentType)[keyof typeof AttachmentType];